apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ${releaseName}-kustomize
  namespace: ${releaseNamespace}
spec:
  interval: 10m
  path: ./applications/katib/upstream/installs/katib-with-kubeflow
  prune: true
  sourceRef:
    kind: GitRepository
    name: ${releaseName}-manifests
    namespace: ${releaseNamespace}
  targetNamespace: ${releaseNamespace}
  timeout: 5m
  wait: true
---
