apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: ${releaseName}-chart
  namespace: ${releaseNamespace}
spec:
  interval: 6h0m0s
  ref:
    tag: "38.0.2"
  url: oci://ghcr.io/traefik/helm/traefik
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: ${releaseNamespace}
spec:
  chartRef:
    kind: OCIRepository
    name: ${releaseName}-chart
    namespace: ${releaseNamespace}
  install:
    crds: CreateReplace
    createNamespace: true
    remediation:
      retries: 30
    timeout: 10m0s
  interval: 15s
  targetNamespace: traefik-system
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 30
    timeout: 10m0s
  valuesFrom:
    - kind: ConfigMap
      name: ${releaseName}-config-defaults
---
